name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure --add-dynamic-module=./ngx_http_dyups_module
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
